### PR TITLE
config(Polaris): Disable DEBUG/FINE logs

### PR DESCRIPTION
**Pull request by fivetran-rahulprakash**
closes [T-796533](https://fivetran.height.app/T-796533)

# Description

Disable Debug & Fine logs

Logs: Before changes
image (2)

Logs: After changes
image (3)

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Review by kamaljit-1991 — APPROVED** [review]
@fivetran-rahulprakash do you think the debug logs were helping in debug any issues. In any case I feel we can re-enable if anything we need to investigate.

**Comment by fivetran-rahulprakash** [comment]
> @fivetran-rahulprakash I have 2 questions regarding the change
> 
> 1. did we verify with Debug logs disabling, are we not missing any important log statements which could be helpful in debugging issues later?
> 2. What is the reduction percentage of logs?
> 
> Also can we make prod type config as part of this PR for logging?


> @fivetran-rahulprakash do you think the debug logs were helping in debug any issues. In any case I feel we can re-enable if anything we need to investigate.

@kamaljit-1991 It could be helpful in the worst cases. So far, I can see that all the failure cases have stack trace error logs, so I feel it’s fine to disable the debug mode, and we can re-enable it if needed

**Comment by fivetran-rahulprakash** [comment]
> @fivetran-rahulprakash I have 2 questions regarding the change
> 
> 1. did we verify with Debug logs disabling, are we not missing any important log statements which could be helpful in debugging issues later?
> 2. What is the reduction percentage of logs?
> 
> Also can we make prod type config as part of this PR for logging?

https://github.com/fivetran/polaris/pull/2#issuecomment-2496604248

Reduction percentage varies based on the scenarios. So far, I have seen more than 30% in my testing since it logs all transaction-related information

What do you mean by prod type config? I already have one ticket for logs, we can include it in that PR if needed.

**Comment by fivetran-rahulprakash** [comment]
@fivetran-arunsuri, as discussed, I have added the current production config to this PR.

**Review by fivetran-arunsuri — APPROVED** [review]

**Pull request merged**
